# Generated by Django 3.2 on 2023-11-29 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_dni', models.CharField(max_length=8)),
                ('cliente_telefono', models.CharField(max_length=50)),
                ('cliente_fecha_nacimiento', models.DateField(null=True)),
                ('cliente_direción', models.TextField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_cliente',
            },
        ),
    ]
