# Generated by Django 3.2 on 2023-12-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catego_nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_categoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produc_nombre', models.CharField(max_length=45)),
                ('produc_imagen', models.ImageField(blank=True, upload_to='productos')),
                ('produc_descripcion', models.TextField(null=True)),
                ('produc_precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('produc_cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.categoria')),
            ],
            options={
                'db_table': 'tbl_producto',
            },
        ),
    ]
