# Generated by Django 3.2 on 2023-12-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_pedido_pedidodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalle',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='cantidad',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
