# Generated by Django 3.2 on 2023-12-08 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0006_pedido_direccion_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_nombre', models.CharField(max_length=45)),
                ('cargo_descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_cargo',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_dni', models.CharField(max_length=8)),
                ('empleado_telefono', models.CharField(max_length=50)),
                ('fecha_contrato', models.DateTimeField(auto_now_add=True)),
                ('empleado_direción', models.TextField()),
                ('salario', models.CharField(max_length=45)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.cargo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_empleado',
            },
        ),
        migrations.CreateModel(
            name='Registrar_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regis_pedido_comentario', models.CharField(max_length=200)),
                ('regis_pedido_fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.empleado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.pedido')),
            ],
            options={
                'db_table': 'tbl_registro_pedido',
            },
        ),
        migrations.CreateModel(
            name='Entregar_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entre_pedido_comentario', models.CharField(max_length=200)),
                ('entre_pedido_fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.empleado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.pedido')),
            ],
            options={
                'db_table': 'tbl_entrega_pedido',
            },
        ),
    ]
