# Generated by Django 3.2 on 2023-12-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_cargo_empleado_entregar_pedido_registrar_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregar_pedido',
            name='entre_pedido_comentario',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entregar_pedido',
            name='entre_pedido_fecha_entrega',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrar_pedido',
            name='regis_pedido_comentario',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrar_pedido',
            name='regis_pedido_fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
