# Generated by Django 3.2 on 2023-12-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20231208_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregar_pedido',
            name='entre_pedido_fecha_entrega',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
