# Generated by Django 3.2 on 2023-12-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_entregar_pedido_entre_pedido_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregar_pedido',
            name='entre_pedido_numero',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entregar_pedido',
            name='entre_pedido_fecha_entrega',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
