# Generated by Django 3.2 on 2023-12-08 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_entregar_pedido_entre_pedido_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregar_pedido',
            name='entre_pedido_fecha_entrega',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
