# Generated by Django 3.2 on 2023-12-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_entregar_pedido_entre_pedido_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregar_pedido',
            name='entre_pedido_fecha_entrega',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
